### ISSUE TITLE
Start Minimized to Tray

### ISSUE THREAD

**Issue by burritosoftware** [DismissedGuy/wiimmfi-rpc#16]
With this option enabled, you could have the program idling in the background in the system tray. It will startup naturally like this and when closed will stay in the system tray.

---

# Function

The icon will be of the Wiimmfi Logo.
The logo itself will be black & white when no game is detected, and colored when a game is detected.
A small dot will be in the bottom right of this icon. It is green for when the presence is on, and red for when the presence is off. Every time from a new boot of the program, it will be on, just if you forget to turn it back on.

Left-clicking this icon will toggle the presence and the dot on and off.
Right clicking will show a context menu where you can open the full window, or fully close the program.

**Comment by malmeloo** [comment]
Thanks for the suggestion, I pushed the last commits for this to prerelease earlier today.

I did make some small changes to the suggested implementation, I'll just list everything below for completion purposes:
* Upon starting the program, it will add the icon to the system tray regardless of whether you have the program open or not.
* Closing the program will now simply hide the main window by default; the first time you do this, a message will be shown explaining the system tray icon. To completely quit the program, you can right-click on the icon and press "Quit." There is a config value that changes this behavior and completely closes the program when clicking "x", but I have not added this to the settings tab yet because it's getting a bit cluttered and I want to find a solution to that first.
* Left-clicking (primary button) on the icon will open the program. I made it this way because I feel like this makes more sense, since it's the default behavior for a lot of other programs as well.
* Right-clicking (secondary button) on the icon will open a context menu. This menu has a version string at the top and three buttons to open or quit the program and to toggle game detection.
* Starting the program with the --start-minimized argument will make it start minimized to the system tray.
* Hovering over the icon will give you a short status message.

The icon behaves like this:
* Game detection disabled -> greyed out Wiimmfi logo
* Game detection enabled, no online games found -> Colored Wiimmfi logo, red dot in the top right
* Game detection enabled, online game found -> Colored Wiimmfi logo, green dot in the top right

Let me know what you think of this implementation.

**Comment by burritosoftware** [comment]
Great implementation! I dig it.

**Comment by malmeloo** [comment]
Since this has now been implemented, I'll go ahead and close this issue.

**Comment by burritosoftware** [comment]
Hey @DismissedGuy, been awhile. I downloaded 1.7.5 on my new PC and ran it, the icon is not in the tray. When I click X I get not message about it, and when I check task manager it looks like it's still hanging around in the background.

**Comment by malmeloo** [comment]
Hey! This is a known problem, it turned out to be an issue with how the program is packaged. I haven't officially released a fix yet, but the current project on master builds releases that work just fine.

Here's a link to a build on GH Actions: https://github.com/DismissedGuy/wiimmfi-rpc/actions/runs/774676686#artifacts

Note that the zip structure is a little weird, that still needs to be fixed.
